#define IDM_CONTENTS    10
#define IDM_SEARCHON    15
#define IDM_USE         20
#define IDM_ABOUT       35

#define IDM_NEW_P       40
#define IDM_NEW_C       45
#define IDM_OPEN_P      50
#define IDM_OPEN_C      55
#define IDM_SAVE_P      60
#define IDM_SAVE_C      65
#define IDM_SAVEAS_P    70
#define IDM_SAVEAS_C    75
#define IDM_PRINT_P     80
#define IDM_PRINT_C     85
#define IDM_EXIT        90

#define IDM_UNDO        95
#define IDM_CUT         100
#define IDM_COPY        105
#define IDM_PASTE       110
#define IDM_CLEAR       115

#define IDM_P_ADD       120
#define IDM_C_ADD       125
#define IDM_R_ADD       130

#define IDM_P_DELETE    135
#define IDM_C_DELETE    140
#define IDM_R_DELETE    145

#define IDM_P_SEARCH    150
#define IDM_C_SEARCH    155
#define IDM_P_SORT      160
#define IDM_C_SORT      165
#define IDM_R_SORT      170
#define IDM_GRAPH       175
#define IDM_HANDICAP    176

#define IDD_PFIRST      180
#define IDD_PLAST       181
#define IDD_PSTREET     182
#define IDD_PCITY       183
#define IDD_PSTATE      184
#define IDD_PZIP        185
#define IDD_PPHONE      186
#define IDD_PINDEX      215
#define IDD_PSCROLL     220
#define IDD_RLIST       225

#define IDD_SC_1        301
#define IDD_SC_2        302
#define IDD_SC_3        303
#define IDD_SC_4        304
#define IDD_SC_5        305
#define IDD_SC_6        306
#define IDD_SC_7        307
#define IDD_SC_8        308
#define IDD_SC_9        309
#define IDD_SC_10       310
#define IDD_SC_11       311
#define IDD_SC_12       312
#define IDD_SC_13       313
#define IDD_SC_14       314
#define IDD_SC_15       315
#define IDD_SC_16       316
#define IDD_SC_17       317
#define IDD_SC_18       318

#define IDD_CNAME       400
#define IDD_CSTREET     401
#define IDD_CCITY       402
#define IDD_CSTATE      403
#define IDD_CZIP        404
#define IDD_CPHONE      405
#define IDD_CRATING     406
#define IDD_CSCROLL     430
#define IDD_CINDEX      435

#define IDD_P_1         501
#define IDD_P_2         502
#define IDD_P_3         503
#define IDD_P_4         504
#define IDD_P_5         505
#define IDD_P_6         506
#define IDD_P_7         507
#define IDD_P_8         508
#define IDD_P_9         509
#define IDD_P_10        510
#define IDD_P_11        511
#define IDD_P_12        512
#define IDD_P_13        513
#define IDD_P_14        514
#define IDD_P_15        515
#define IDD_P_16        516
#define IDD_P_17        517
#define IDD_P_18        518

#define IDD_H_1         601
#define IDD_H_2         602
#define IDD_H_3         603
#define IDD_H_4         604
#define IDD_H_5         605
#define IDD_H_6         606
#define IDD_H_7         607
#define IDD_H_8         608
#define IDD_H_9         609
#define IDD_H_10        610
#define IDD_H_11        611
#define IDD_H_12        612
#define IDD_H_13        613
#define IDD_H_14        614
#define IDD_H_15        615
#define IDD_H_16        616
#define IDD_H_17        617
#define IDD_H_18        618

#define IDD_FNAME       700
#define IDD_FPATH       705
#define IDD_FLIST       710

#define IDD_DC_ROUNDS   715
#define IDD_DC_CNAME    720
#define IDD_ND_CNAME    725

#define IDD_ND_MM       730
#define IDD_ND_DD       735
#define IDD_ND_YY       740

#define IDD_S_BEGINNING 745
#define IDD_S_CURRENT   750
#define IDD_S_FIRSTNAME 755
#define IDD_S_LASTNAME  760
#define IDD_S_COURSE    765
#define IDD_S_STREET    770
#define IDD_S_CITY      775
#define IDD_S_STATE     780
#define IDD_S_ZIP       785
#define IDD_S_PHONE     790
#define IDD_S_SEARCHFOR 795
#define IDD_HNUMROUNDS  805
#define IDD_HANDICAP    810
